### ISSUE TITLE
Dark theme / CSS refactor

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#185]

**Comment by heyitsmeuralex** [comment]
Note #187 removes the `:host` class prefix stuff in favour of static classnames (e.g. `._xyz123` -> `.channel-list`), making theming a lot more viable.

**Comment by towerofnix** [comment]
Generally, I think it would make sense to refactor the CSS to use more descriptive variable names, e.g. "pane background". For example:

```css
body {
  --gray-900: #fff;
  --pane-background: var(--gray-900);
}

.sidebar (or :host, whatever) {
  background: var(--pane-background);
}
```
